import { CountryStat } from '../types';

export interface CountryInfo {
  code: string;
  name: string;
  flag: string;
  continent: string; // AF, AN, AS, EU, NA, OC, SA
}

export function getFlagEmoji(countryCode: string): string {
  if (!countryCode || countryCode.length !== 2) return '🌐';
  const codePoints = countryCode
    .toUpperCase()
    .split('')
    .map((char) => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}

export const COUNTRIES: CountryInfo[] = [
  { code: 'AF', name: 'Afghanistan', flag: getFlagEmoji('AF'), continent: 'AS' },
  { code: 'AL', name: 'Albania', flag: getFlagEmoji('AL'), continent: 'EU' },
  { code: 'DZ', name: 'Algeria', flag: getFlagEmoji('DZ'), continent: 'AF' },
  { code: 'AD', name: 'Andorra', flag: getFlagEmoji('AD'), continent: 'EU' },
  { code: 'AO', name: 'Angola', flag: getFlagEmoji('AO'), continent: 'AF' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: getFlagEmoji('AG'), continent: 'NA' },
  { code: 'AR', name: 'Argentina', flag: getFlagEmoji('AR'), continent: 'SA' },
  { code: 'AM', name: 'Armenia', flag: getFlagEmoji('AM'), continent: 'AS' },
  { code: 'AU', name: 'Australia', flag: getFlagEmoji('AU'), continent: 'OC' },
  { code: 'AT', name: 'Austria', flag: getFlagEmoji('AT'), continent: 'EU' },
  { code: 'AZ', name: 'Azerbaijan', flag: getFlagEmoji('AZ'), continent: 'AS' },
  { code: 'BS', name: 'Bahamas', flag: getFlagEmoji('BS'), continent: 'NA' },
  { code: 'BH', name: 'Bahrain', flag: getFlagEmoji('BH'), continent: 'AS' },
  { code: 'BD', name: 'Bangladesh', flag: getFlagEmoji('BD'), continent: 'AS' },
  { code: 'BB', name: 'Barbados', flag: getFlagEmoji('BB'), continent: 'NA' },
  { code: 'BY', name: 'Belarus', flag: getFlagEmoji('BY'), continent: 'EU' },
  { code: 'BE', name: 'Belgium', flag: getFlagEmoji('BE'), continent: 'EU' },
  { code: 'BZ', name: 'Belize', flag: getFlagEmoji('BZ'), continent: 'NA' },
  { code: 'BJ', name: 'Benin', flag: getFlagEmoji('BJ'), continent: 'AF' },
  { code: 'BT', name: 'Bhutan', flag: getFlagEmoji('BT'), continent: 'AS' },
  { code: 'BO', name: 'Bolivia', flag: getFlagEmoji('BO'), continent: 'SA' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: getFlagEmoji('BA'), continent: 'EU' },
  { code: 'BW', name: 'Botswana', flag: getFlagEmoji('BW'), continent: 'AF' },
  { code: 'BR', name: 'Brazil', flag: getFlagEmoji('BR'), continent: 'SA' },
  { code: 'BN', name: 'Brunei', flag: getFlagEmoji('BN'), continent: 'AS' },
  { code: 'BG', name: 'Bulgaria', flag: getFlagEmoji('BG'), continent: 'EU' },
  { code: 'BF', name: 'Burkina Faso', flag: getFlagEmoji('BF'), continent: 'AF' },
  { code: 'BI', name: 'Burundi', flag: getFlagEmoji('BI'), continent: 'AF' },
  { code: 'KH', name: 'Cambodia', flag: getFlagEmoji('KH'), continent: 'AS' },
  { code: 'CM', name: 'Cameroon', flag: getFlagEmoji('CM'), continent: 'AF' },
  { code: 'CA', name: 'Canada', flag: getFlagEmoji('CA'), continent: 'NA' },
  { code: 'CV', name: 'Cape Verde', flag: getFlagEmoji('CV'), continent: 'AF' },
  { code: 'CF', name: 'Central African Republic', flag: getFlagEmoji('CF'), continent: 'AF' },
  { code: 'TD', name: 'Chad', flag: getFlagEmoji('TD'), continent: 'AF' },
  { code: 'CL', name: 'Chile', flag: getFlagEmoji('CL'), continent: 'SA' },
  { code: 'CN', name: 'China', flag: getFlagEmoji('CN'), continent: 'AS' },
  { code: 'CO', name: 'Colombia', flag: getFlagEmoji('CO'), continent: 'SA' },
  { code: 'KM', name: 'Comoros', flag: getFlagEmoji('KM'), continent: 'AF' },
  { code: 'CG', name: 'Congo (Brazzaville)', flag: getFlagEmoji('CG'), continent: 'AF' },
  { code: 'CD', name: 'Congo (Kinshasa)', flag: getFlagEmoji('CD'), continent: 'AF' },
  { code: 'CR', name: 'Costa Rica', flag: getFlagEmoji('CR'), continent: 'NA' },
  { code: 'HR', name: 'Croatia', flag: getFlagEmoji('HR'), continent: 'EU' },
  { code: 'CU', name: 'Cuba', flag: getFlagEmoji('CU'), continent: 'NA' },
  { code: 'CY', name: 'Cyprus', flag: getFlagEmoji('CY'), continent: 'EU' },
  { code: 'CZ', name: 'Czech Republic', flag: getFlagEmoji('CZ'), continent: 'EU' },
  { code: 'DK', name: 'Denmark', flag: getFlagEmoji('DK'), continent: 'EU' },
  { code: 'DJ', name: 'Djibouti', flag: getFlagEmoji('DJ'), continent: 'AF' },
  { code: 'DM', name: 'Dominica', flag: getFlagEmoji('DM'), continent: 'NA' },
  { code: 'DO', name: 'Dominican Republic', flag: getFlagEmoji('DO'), continent: 'NA' },
  { code: 'EC', name: 'Ecuador', flag: getFlagEmoji('EC'), continent: 'SA' },
  { code: 'EG', name: 'Egypt', flag: getFlagEmoji('EG'), continent: 'AF' },
  { code: 'SV', name: 'El Salvador', flag: getFlagEmoji('SV'), continent: 'NA' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: getFlagEmoji('GQ'), continent: 'AF' },
  { code: 'ER', name: 'Eritrea', flag: getFlagEmoji('ER'), continent: 'AF' },
  { code: 'EE', name: 'Estonia', flag: getFlagEmoji('EE'), continent: 'EU' },
  { code: 'SZ', name: 'Eswatini', flag: getFlagEmoji('SZ'), continent: 'AF' },
  { code: 'ET', name: 'Ethiopia', flag: getFlagEmoji('ET'), continent: 'AF' },
  { code: 'FJ', name: 'Fiji', flag: getFlagEmoji('FJ'), continent: 'OC' },
  { code: 'FI', name: 'Finland', flag: getFlagEmoji('FI'), continent: 'EU' },
  { code: 'FR', name: 'France', flag: getFlagEmoji('FR'), continent: 'EU' },
  { code: 'GA', name: 'Gabon', flag: getFlagEmoji('GA'), continent: 'AF' },
  { code: 'GM', name: 'Gambia', flag: getFlagEmoji('GM'), continent: 'AF' },
  { code: 'GE', name: 'Georgia', flag: getFlagEmoji('GE'), continent: 'AS' },
  { code: 'DE', name: 'Germany', flag: getFlagEmoji('DE'), continent: 'EU' },
  { code: 'GH', name: 'Ghana', flag: getFlagEmoji('GH'), continent: 'AF' },
  { code: 'GR', name: 'Greece', flag: getFlagEmoji('GR'), continent: 'EU' },
  { code: 'GD', name: 'Grenada', flag: getFlagEmoji('GD'), continent: 'NA' },
  { code: 'GT', name: 'Guatemala', flag: getFlagEmoji('GT'), continent: 'NA' },
  { code: 'GN', name: 'Guinea', flag: getFlagEmoji('GN'), continent: 'AF' },
  { code: 'GW', name: 'Guinea-Bissau', flag: getFlagEmoji('GW'), continent: 'AF' },
  { code: 'GY', name: 'Guyana', flag: getFlagEmoji('GY'), continent: 'SA' },
  { code: 'HT', name: 'Haiti', flag: getFlagEmoji('HT'), continent: 'NA' },
  { code: 'HN', name: 'Honduras', flag: getFlagEmoji('HN'), continent: 'NA' },
  { code: 'HK', name: 'Hong Kong', flag: getFlagEmoji('HK'), continent: 'AS' },
  { code: 'HU', name: 'Hungary', flag: getFlagEmoji('HU'), continent: 'EU' },
  { code: 'IS', name: 'Iceland', flag: getFlagEmoji('IS'), continent: 'EU' },
  { code: 'IN', name: 'India', flag: getFlagEmoji('IN'), continent: 'AS' },
  { code: 'ID', name: 'Indonesia', flag: getFlagEmoji('ID'), continent: 'AS' },
  { code: 'IR', name: 'Iran', flag: getFlagEmoji('IR'), continent: 'AS' },
  { code: 'IQ', name: 'Iraq', flag: getFlagEmoji('IQ'), continent: 'AS' },
  { code: 'IE', name: 'Ireland', flag: getFlagEmoji('IE'), continent: 'EU' },
  { code: 'IL', name: 'Israel', flag: getFlagEmoji('IL'), continent: 'AS' },
  { code: 'IT', name: 'Italy', flag: getFlagEmoji('IT'), continent: 'EU' },
  { code: 'JM', name: 'Jamaica', flag: getFlagEmoji('JM'), continent: 'NA' },
  { code: 'JP', name: 'Japan', flag: getFlagEmoji('JP'), continent: 'AS' },
  { code: 'JO', name: 'Jordan', flag: getFlagEmoji('JO'), continent: 'AS' },
  { code: 'KZ', name: 'Kazakhstan', flag: getFlagEmoji('KZ'), continent: 'AS' },
  { code: 'KE', name: 'Kenya', flag: getFlagEmoji('KE'), continent: 'AF' },
  { code: 'KI', name: 'Kiribati', flag: getFlagEmoji('KI'), continent: 'OC' },
  { code: 'KP', name: 'North Korea', flag: getFlagEmoji('KP'), continent: 'AS' },
  { code: 'KR', name: 'South Korea', flag: getFlagEmoji('KR'), continent: 'AS' },
  { code: 'KW', name: 'Kuwait', flag: getFlagEmoji('KW'), continent: 'AS' },
  { code: 'KG', name: 'Kyrgyzstan', flag: getFlagEmoji('KG'), continent: 'AS' },
  { code: 'LA', name: 'Laos', flag: getFlagEmoji('LA'), continent: 'AS' },
  { code: 'LV', name: 'Latvia', flag: getFlagEmoji('LV'), continent: 'EU' },
  { code: 'LB', name: 'Lebanon', flag: getFlagEmoji('LB'), continent: 'AS' },
  { code: 'LS', name: 'Lesotho', flag: getFlagEmoji('LS'), continent: 'AF' },
  { code: 'LR', name: 'Liberia', flag: getFlagEmoji('LR'), continent: 'AF' },
  { code: 'LY', name: 'Libya', flag: getFlagEmoji('LY'), continent: 'AF' },
  { code: 'LI', name: 'Liechtenstein', flag: getFlagEmoji('LI'), continent: 'EU' },
  { code: 'LT', name: 'Lithuania', flag: getFlagEmoji('LT'), continent: 'EU' },
  { code: 'LU', name: 'Luxembourg', flag: getFlagEmoji('LU'), continent: 'EU' },
  { code: 'MO', name: 'Macau', flag: getFlagEmoji('MO'), continent: 'AS' },
  { code: 'MG', name: 'Madagascar', flag: getFlagEmoji('MG'), continent: 'AF' },
  { code: 'MW', name: 'Malawi', flag: getFlagEmoji('MW'), continent: 'AF' },
  { code: 'MY', name: 'Malaysia', flag: getFlagEmoji('MY'), continent: 'AS' },
  { code: 'MV', name: 'Maldives', flag: getFlagEmoji('MV'), continent: 'AS' },
  { code: 'ML', name: 'Mali', flag: getFlagEmoji('ML'), continent: 'AF' },
  { code: 'MT', name: 'Malta', flag: getFlagEmoji('MT'), continent: 'EU' },
  { code: 'MH', name: 'Marshall Islands', flag: getFlagEmoji('MH'), continent: 'OC' },
  { code: 'MR', name: 'Mauritania', flag: getFlagEmoji('MR'), continent: 'AF' },
  { code: 'MU', name: 'Mauritius', flag: getFlagEmoji('MU'), continent: 'AF' },
  { code: 'MX', name: 'Mexico', flag: getFlagEmoji('MX'), continent: 'NA' },
  { code: 'FM', name: 'Micronesia', flag: getFlagEmoji('FM'), continent: 'OC' },
  { code: 'MD', name: 'Moldova', flag: getFlagEmoji('MD'), continent: 'EU' },
  { code: 'MC', name: 'Monaco', flag: getFlagEmoji('MC'), continent: 'EU' },
  { code: 'MN', name: 'Mongolia', flag: getFlagEmoji('MN'), continent: 'AS' },
  { code: 'ME', name: 'Montenegro', flag: getFlagEmoji('ME'), continent: 'EU' },
  { code: 'MA', name: 'Morocco', flag: getFlagEmoji('MA'), continent: 'AF' },
  { code: 'MZ', name: 'Mozambique', flag: getFlagEmoji('MZ'), continent: 'AF' },
  { code: 'MM', name: 'Myanmar', flag: getFlagEmoji('MM'), continent: 'AS' },
  { code: 'NA', name: 'Namibia', flag: getFlagEmoji('NA'), continent: 'AF' },
  { code: 'NR', name: 'Nauru', flag: getFlagEmoji('NR'), continent: 'OC' },
  { code: 'NP', name: 'Nepal', flag: getFlagEmoji('NP'), continent: 'AS' },
  { code: 'NL', name: 'Netherlands', flag: getFlagEmoji('NL'), continent: 'EU' },
  { code: 'NZ', name: 'New Zealand', flag: getFlagEmoji('NZ'), continent: 'OC' },
  { code: 'NI', name: 'Nicaragua', flag: getFlagEmoji('NI'), continent: 'NA' },
  { code: 'NE', name: 'Niger', flag: getFlagEmoji('NE'), continent: 'AF' },
  { code: 'NG', name: 'Nigeria', flag: getFlagEmoji('NG'), continent: 'AF' },
  { code: 'MK', name: 'North Macedonia', flag: getFlagEmoji('MK'), continent: 'EU' },
  { code: 'NO', name: 'Norway', flag: getFlagEmoji('NO'), continent: 'EU' },
  { code: 'OM', name: 'Oman', flag: getFlagEmoji('OM'), continent: 'AS' },
  { code: 'PK', name: 'Pakistan', flag: getFlagEmoji('PK'), continent: 'AS' },
  { code: 'PW', name: 'Palau', flag: getFlagEmoji('PW'), continent: 'OC' },
  { code: 'PS', name: 'Palestine', flag: getFlagEmoji('PS'), continent: 'AS' },
  { code: 'PA', name: 'Panama', flag: getFlagEmoji('PA'), continent: 'NA' },
  { code: 'PG', name: 'Papua New Guinea', flag: getFlagEmoji('PG'), continent: 'OC' },
  { code: 'PY', name: 'Paraguay', flag: getFlagEmoji('PY'), continent: 'SA' },
  { code: 'PE', name: 'Peru', flag: getFlagEmoji('PE'), continent: 'SA' },
  { code: 'PH', name: 'Philippines', flag: getFlagEmoji('PH'), continent: 'AS' },
  { code: 'PL', name: 'Poland', flag: getFlagEmoji('PL'), continent: 'EU' },
  { code: 'PT', name: 'Portugal', flag: getFlagEmoji('PT'), continent: 'EU' },
  { code: 'PR', name: 'Puerto Rico', flag: getFlagEmoji('PR'), continent: 'NA' },
  { code: 'QA', name: 'Qatar', flag: getFlagEmoji('QA'), continent: 'AS' },
  { code: 'RO', name: 'Romania', flag: getFlagEmoji('RO'), continent: 'EU' },
  { code: 'RU', name: 'Russia', flag: getFlagEmoji('RU'), continent: 'EU' },
  { code: 'RW', name: 'Rwanda', flag: getFlagEmoji('RW'), continent: 'AF' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: getFlagEmoji('KN'), continent: 'NA' },
  { code: 'LC', name: 'Saint Lucia', flag: getFlagEmoji('LC'), continent: 'NA' },
  { code: 'VC', name: 'Saint Vincent and Grenadines', flag: getFlagEmoji('VC'), continent: 'NA' },
  { code: 'WS', name: 'Samoa', flag: getFlagEmoji('WS'), continent: 'OC' },
  { code: 'SM', name: 'San Marino', flag: getFlagEmoji('SM'), continent: 'EU' },
  { code: 'ST', name: 'Sao Tome and Principe', flag: getFlagEmoji('ST'), continent: 'AF' },
  { code: 'SA', name: 'Saudi Arabia', flag: getFlagEmoji('SA'), continent: 'AS' },
  { code: 'SN', name: 'Senegal', flag: getFlagEmoji('SN'), continent: 'AF' },
  { code: 'RS', name: 'Serbia', flag: getFlagEmoji('RS'), continent: 'EU' },
  { code: 'SC', name: 'Seychelles', flag: getFlagEmoji('SC'), continent: 'AF' },
  { code: 'SL', name: 'Sierra Leone', flag: getFlagEmoji('SL'), continent: 'AF' },
  { code: 'SG', name: 'Singapore', flag: getFlagEmoji('SG'), continent: 'AS' },
  { code: 'SK', name: 'Slovakia', flag: getFlagEmoji('SK'), continent: 'EU' },
  { code: 'SI', name: 'Slovenia', flag: getFlagEmoji('SI'), continent: 'EU' },
  { code: 'SB', name: 'Solomon Islands', flag: getFlagEmoji('SB'), continent: 'OC' },
  { code: 'SO', name: 'Somalia', flag: getFlagEmoji('SO'), continent: 'AF' },
  { code: 'ZA', name: 'South Africa', flag: getFlagEmoji('ZA'), continent: 'AF' },
  { code: 'SS', name: 'South Sudan', flag: getFlagEmoji('SS'), continent: 'AF' },
  { code: 'ES', name: 'Spain', flag: getFlagEmoji('ES'), continent: 'EU' },
  { code: 'LK', name: 'Sri Lanka', flag: getFlagEmoji('LK'), continent: 'AS' },
  { code: 'SD', name: 'Sudan', flag: getFlagEmoji('SD'), continent: 'AF' },
  { code: 'SR', name: 'Suriname', flag: getFlagEmoji('SR'), continent: 'SA' },
  { code: 'SE', name: 'Sweden', flag: getFlagEmoji('SE'), continent: 'EU' },
  { code: 'CH', name: 'Switzerland', flag: getFlagEmoji('CH'), continent: 'EU' },
  { code: 'SY', name: 'Syria', flag: getFlagEmoji('SY'), continent: 'AS' },
  { code: 'TW', name: 'Taiwan', flag: getFlagEmoji('TW'), continent: 'AS' },
  { code: 'TJ', name: 'Tajikistan', flag: getFlagEmoji('TJ'), continent: 'AS' },
  { code: 'TZ', name: 'Tanzania', flag: getFlagEmoji('TZ'), continent: 'AF' },
  { code: 'TH', name: 'Thailand', flag: getFlagEmoji('TH'), continent: 'AS' },
  { code: 'TL', name: 'Timor-Leste', flag: getFlagEmoji('TL'), continent: 'AS' },
  { code: 'TG', name: 'Togo', flag: getFlagEmoji('TG'), continent: 'AF' },
  { code: 'TO', name: 'Tonga', flag: getFlagEmoji('TO'), continent: 'OC' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: getFlagEmoji('TT'), continent: 'NA' },
  { code: 'TN', name: 'Tunisia', flag: getFlagEmoji('TN'), continent: 'AF' },
  { code: 'TR', name: 'Turkey', flag: getFlagEmoji('TR'), continent: 'AS' },
  { code: 'TM', name: 'Turkmenistan', flag: getFlagEmoji('TM'), continent: 'AS' },
  { code: 'TV', name: 'Tuvalu', flag: getFlagEmoji('TV'), continent: 'OC' },
  { code: 'UG', name: 'Uganda', flag: getFlagEmoji('UG'), continent: 'AF' },
  { code: 'UA', name: 'Ukraine', flag: getFlagEmoji('UA'), continent: 'EU' },
  { code: 'AE', name: 'United Arab Emirates', flag: getFlagEmoji('AE'), continent: 'AS' },
  { code: 'GB', name: 'United Kingdom', flag: getFlagEmoji('GB'), continent: 'EU' },
  { code: 'US', name: 'United States', flag: getFlagEmoji('US'), continent: 'NA' },
  { code: 'UY', name: 'Uruguay', flag: getFlagEmoji('UY'), continent: 'SA' },
  { code: 'UZ', name: 'Uzbekistan', flag: getFlagEmoji('UZ'), continent: 'AS' },
  { code: 'VU', name: 'Vanuatu', flag: getFlagEmoji('VU'), continent: 'OC' },
  { code: 'VA', name: 'Vatican City', flag: getFlagEmoji('VA'), continent: 'EU' },
  { code: 'VE', name: 'Venezuela', flag: getFlagEmoji('VE'), continent: 'SA' },
  { code: 'VN', name: 'Vietnam', flag: getFlagEmoji('VN'), continent: 'AS' },
  { code: 'YE', name: 'Yemen', flag: getFlagEmoji('YE'), continent: 'AS' },
  { code: 'ZM', name: 'Zambia', flag: getFlagEmoji('ZM'), continent: 'AF' },
  { code: 'ZW', name: 'Zimbabwe', flag: getFlagEmoji('ZW'), continent: 'AF' },
];

export const AVATARS = [
  '⚡', '🐆', '🦅', '🎯', '🚀', '🔥', '👑', '🐺', '🐉', '🤖', '👾', '🐱', '🦊', '🦁', '🐼', '🦄'
];

export function getCountryFlag(code: string): string {
  if (!code) return '🌐';
  const found = COUNTRIES.find((c) => c.code.toUpperCase() === code.toUpperCase());
  return found ? found.flag : getFlagEmoji(code);
}

export function getCountryName(code: string): string {
  if (!code) return 'Worldwide';
  const found = COUNTRIES.find((c) => c.code.toUpperCase() === code.toUpperCase());
  return found ? found.name : code.toUpperCase();
}

export const INITIAL_COUNTRY_STATS: CountryStat[] = [
  { country: 'JP', name: 'Japan', flag: getFlagEmoji('JP'), avgMs: 182, totalPlayers: 14200, bestMs: 138 },
  { country: 'KR', name: 'South Korea', flag: getFlagEmoji('KR'), avgMs: 185, totalPlayers: 12800, bestMs: 135 },
  { country: 'DE', name: 'Germany', flag: getFlagEmoji('DE'), avgMs: 191, totalPlayers: 18400, bestMs: 141 },
  { country: 'SE', name: 'Sweden', flag: getFlagEmoji('SE'), avgMs: 193, totalPlayers: 8900, bestMs: 144 },
  { country: 'US', name: 'United States', flag: getFlagEmoji('US'), avgMs: 198, totalPlayers: 48200, bestMs: 139 },
  { country: 'GB', name: 'United Kingdom', flag: getFlagEmoji('GB'), avgMs: 201, totalPlayers: 21500, bestMs: 143 },
  { country: 'CA', name: 'Canada', flag: getFlagEmoji('CA'), avgMs: 204, totalPlayers: 11300, bestMs: 146 },
  { country: 'AU', name: 'Australia', flag: getFlagEmoji('AU'), avgMs: 206, totalPlayers: 9400, bestMs: 148 },
  { country: 'BR', name: 'Brazil', flag: getFlagEmoji('BR'), avgMs: 209, totalPlayers: 16700, bestMs: 142 },
  { country: 'FR', name: 'France', flag: getFlagEmoji('FR'), avgMs: 211, totalPlayers: 13900, bestMs: 147 },
  { country: 'IN', name: 'India', flag: getFlagEmoji('IN'), avgMs: 214, totalPlayers: 31200, bestMs: 145 },
  { country: 'ES', name: 'Spain', flag: getFlagEmoji('ES'), avgMs: 216, totalPlayers: 10800, bestMs: 151 },
];

export function getPercentileRating(ms: number): { rating: string; percentile: number; color: string; icon: string } {
  if (ms < 150) return { rating: 'Godlike Reflexes', percentile: 99.8, color: 'text-amber-400', icon: '⚡' };
  if (ms < 175) return { rating: 'Pro Gamer Speed', percentile: 98.2, color: 'text-purple-400', icon: '🦅' };
  if (ms < 200) return { rating: 'Cheetah Reflexes', percentile: 92.5, color: 'text-emerald-400', icon: '🐆' };
  if (ms < 230) return { rating: 'Fast Human', percentile: 81.0, color: 'text-cyan-400', icon: '🚀' };
  if (ms < 270) return { rating: 'Average Human', percentile: 52.0, color: 'text-blue-400', icon: '🧍' };
  if (ms < 320) return { rating: 'Sleepy Eyes', percentile: 25.0, color: 'text-orange-400', icon: '☕' };
  return { rating: 'Turtle Speed', percentile: 8.0, color: 'text-rose-400', icon: '🐢' };
}
